import { useEffect, useState } from 'react';

export default function Flashcards({ cards }) {
  const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false);
  useEffect(() => { setIndex(0); setFlipped(false); }, [cards]);
  useEffect(() => { const onKey = (e) => { if (e.target.tagName === 'TEXTAREA') return; if (e.key === 'ArrowLeft') setIndex((i) => Math.max(0, i - 1)); if (e.key === 'ArrowRight') setIndex((i) => Math.min(cards.length - 1, i + 1)); if (e.code === 'Space') { e.preventDefault(); setFlipped((f) => !f); } }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); }, [cards.length]);
  if (!cards.length) return null; const card = cards[index]; const navigate = (delta) => { setIndex((i) => Math.max(0, Math.min(cards.length - 1, i + delta))); setFlipped(false); };
  return <section className="panel"><div className="section-heading"><div><p className="eyebrow">FLASHCARDS</p><h2>Build lasting recall</h2></div><span className="badge">Card {index + 1} / {cards.length}</span></div><div className="progress"><i style={{ width: `${((index + 1) / cards.length) * 100}%` }}/></div><button className={`flashcard ${flipped ? 'is-flipped' : ''}`} onClick={() => setFlipped(!flipped)} aria-label="Flip flashcard"><div className="card-inner"><div className="card-face"><span>QUESTION</span><strong>{card.question}</strong><small>Click or press Space to reveal answer</small></div><div className="card-face card-back"><span>ANSWER</span><strong>{card.answer}</strong><small>Click or press Space to flip back</small></div></div></button><div className="mt-5 flex justify-between"><button className="secondary-button" onClick={() => navigate(-1)} disabled={!index}>← Previous</button><button className="secondary-button" onClick={() => navigate(1)} disabled={index === cards.length - 1}>Next →</button></div></section>;
}
