import { useEffect, useState } from 'react';

export default function Quiz({ questions }) {
  const [active, setActive] = useState(questions); const [index, setIndex] = useState(0); const [selected, setSelected] = useState(''); const [answers, setAnswers] = useState([]); const [finished, setFinished] = useState(false);
  useEffect(() => { setActive(questions); setIndex(0); setSelected(''); setAnswers([]); setFinished(false); }, [questions]);
  if (!active.length) return null; const question = active[index]; const submit = () => { if (!selected) return; const nextAnswers = [...answers, { question, selected }]; setAnswers(nextAnswers); if (index + 1 === active.length) setFinished(true); else { setIndex(index + 1); setSelected(''); } }; const incorrect = answers.filter(({ question: q, selected: a }) => q.correctAnswer !== a);
  if (finished) return <section className="panel quiz-result"><p className="eyebrow">QUIZ COMPLETE</p><h2>{answers.length - incorrect.length} / {answers.length}</h2><p className="text-slate-500 dark:text-slate-400">{incorrect.length ? `${incorrect.length} question${incorrect.length > 1 ? 's' : ''} to revisit.` : 'Perfect score—excellent work!'}</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button className="secondary-button" onClick={() => { setIndex(0); setSelected(''); setAnswers([]); setFinished(false); }}>Retry all</button>{incorrect.length > 0 && <button className="primary-button" onClick={() => { setActive(incorrect.map((item) => item.question)); setIndex(0); setSelected(''); setAnswers([]); setFinished(false); }}>Retry incorrect questions</button>}</div></section>;
  return <section className="panel"><div className="section-heading"><div><p className="eyebrow">KNOWLEDGE CHECK</p><h2>Test yourself</h2></div><span className="badge">{index + 1} / {active.length}</span></div><div className="progress"><i style={{ width: `${((index + 1) / active.length) * 100}%` }}/></div><h3 className="mt-7 text-lg font-semibold">{question.question}</h3><fieldset className="mt-5 grid gap-3"><legend className="sr-only">Answer options</legend>{question.options.map((option) => <label key={option} className={`option ${selected === option ? 'selected' : ''}`}><input type="radio" name="answer" value={option} checked={selected === option} onChange={(e) => setSelected(e.target.value)}/><span>{option}</span></label>)}</fieldset><div className="mt-6 flex justify-end"><button className="primary-button" onClick={submit} disabled={!selected}>{index + 1 === active.length ? 'See results' : 'Submit answer →'}</button></div></section>;
}
